# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forklift < Formula
  desc "A CLI tool for managing merge branches across repositories using Google Sheets"
  homepage "https://github.com/afk-ankit/forklift"
  version "0.0.7"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.7/forklift_Darwin_x86_64.tar.gz"
      sha256 "2784e31baaaf79e21aadc4f3f5d406105b424dec76e89493512694888706b095"

      def install
        bin.install "forklift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.7/forklift_Darwin_arm64.tar.gz"
      sha256 "9da289b333e4ccad267a573e8c3089b9447552261033225ccb66818267e0a82e"

      def install
        bin.install "forklift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.7/forklift_Linux_x86_64.tar.gz"
      sha256 "da1c041067ccb11c657f9d16dd5aececa4ebc84efe732e1f65f2b210b6fda8a4"
      def install
        bin.install "forklift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.7/forklift_Linux_arm64.tar.gz"
      sha256 "62cbbe50b01affd276d32b41ecc92ffd6acfe25d4fd48ad26bc375d0096ddc72"
      def install
        bin.install "forklift"
      end
    end
  end

  def caveats
    <<~EOS
      Run `forklift init` to get started.
    EOS
  end
end
