# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forklift < Formula
  desc "A CLI tool for managing merge branches across repositories using Google Sheets"
  homepage "https://github.com/afk-ankit/forklift"
  version "0.0.10"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.10/forklift_Darwin_x86_64.tar.gz"
      sha256 "ecf41e62a9f2bbd419fd6587c2f896f216e0f1dd2b99507d79df77924e783122"

      define_method(:install) do
        bin.install "forklift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.10/forklift_Darwin_arm64.tar.gz"
      sha256 "0fd394a10592f2e67bfadf41972bc77b78bb65e56b573fe79c2e62ff9567f4b6"

      define_method(:install) do
        bin.install "forklift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.10/forklift_Linux_x86_64.tar.gz"
      sha256 "6a7f9e757107950fd441926c33558bd4ae2b9bd823ba669e5a007e89b168dc84"
      define_method(:install) do
        bin.install "forklift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.10/forklift_Linux_arm64.tar.gz"
      sha256 "1a8757ebc9f8a651bcc5a11e17476cb5f6a1660bb190e7b1e4a02a4397cba3f0"
      define_method(:install) do
        bin.install "forklift"
      end
    end
  end

  def caveats
    <<~EOS
      Run `forklift init` to get started.
    EOS
  end
end
