# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forklift < Formula
  desc "A CLI tool for managing merge branches across repositories using Google Sheets"
  homepage "https://github.com/afk-ankit/forklift"
  version "0.0.12"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.12/forklift_Darwin_x86_64.tar.gz"
      sha256 "fa1c38b1cd2ace82b39433528ee777b9fff4a35389289f3677646226c56c8246"

      define_method(:install) do
        bin.install "forklift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.12/forklift_Darwin_arm64.tar.gz"
      sha256 "f2a1c838e2433230ef29acf0ee5395be48ab6b8e616d034809f0c8624d34ad0c"

      define_method(:install) do
        bin.install "forklift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.12/forklift_Linux_x86_64.tar.gz"
      sha256 "12d28adbe2eed5a92ce7af45d853c373766c716b8dc3d93078ce7e2610dee848"
      define_method(:install) do
        bin.install "forklift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/afk-ankit/forklift/releases/download/v0.0.12/forklift_Linux_arm64.tar.gz"
      sha256 "f8bd5aa4e1db5ce822d6212f12003ede83551d977c032eda28ee29769701e509"
      define_method(:install) do
        bin.install "forklift"
      end
    end
  end

  def caveats
    <<~EOS
      Run `forklift init` to get started.
    EOS
  end
end
